### ISSUE TITLE
->get()->with()

### ISSUE THREAD

**Issue by marcelloh** [vlucas/spot2#154]
If I want 1 record with the relations, I think I should be able to do a ->get()->with()
but it throws me an error:
Call to undefined method Entities\Post::with() in ...\Mappers\Post.php

This means  I have to load the relations myself and inject them into the result?
Seems weird to me.

**Comment by tuupola** [comment]
The `with()` method is used for eager loading to solve N+1 problem and probably only works with collections. There is no advantages to use  `with()` when retrieving only one entity.  You can access relations with their name. If you have something like:
 
```php
class User extends \Spot\Entity
{
    ...
    public static function relations(Mapper $mapper, Entity $entity)
    {
        return [
            "profile" => $mapper->hasOne($entity, "Profile", "user_id")
        ];
    }
}
````

You can then access profile with:

```php
$user =  $spot->mapper("User")->get(1);
print_r($user->profile);
```

**Comment by marcelloh** [comment]
I have a client entity with relations like this:
 'country' => $mapper->belongsTo($entity, 'Entities\Country', 'country_id')
 so I expect, when I do a client->get(), I must be able to use those relations too.

But I made another solution, so it works for me now.

**Comment by FlipEverything** [comment]
Please read @tuupola's comment. You can access the relations with a simple -> operator. If you get() one entity, you don't need to use the with() function. with() is for collections.

```php
$client->country
```

**Comment by tuupola** [comment]
@marcelloh please post meaningful code examples with bug reports. Currently it is hard to tell what you are actually doing.

**Comment by marcelloh** [comment]
Ok, thanks. I think I didn't understand the documentation about belongsto quite well then.
I would say: a user belongs to a country, that why I choose the belongsto.
But I can say: a user has 1 country, so a hasOne is more in place.
though I still don't understand the difference yet, won't be able to tell my kids about it :-)
I will follow your lead: if it is a 1 on 1 : use hasOne!
Thanks again.

**Comment by vlucas** [comment]
Thanks @tuupola and @FlipEverything for answering so quickly! You are both spot on (pun intended). The `with` method is designed for collections to solve the N+1 query problem, and doesn't provide any advantage when only a single record is involved.

You could still technically use it with a single record by creating a `Spot\Query` object:
```php
$mapper->where(['id', 1])->with('country')->first();
```

But like I said, that doesn't really provide any benefit because the same number of queries are executed as:

```php
$user = $mapper->get(1);
$user->country;
```

The only difference is that the relation query is executed when you access the `country` property, so it's lazy-loaded instead of eager-loaded via `with`.
