### ISSUE TITLE
Mapping column names to properties

### ISSUE THREAD

**Issue by smithtonson** [vlucas/spot2#97]
Is there a way to map a column name to the object property name?
I have an "employee_table" table with a PK of "employee_id" but want the proper in the Entity to just be "id", am I missing something or is that not available in Spot2?

**Comment by vlucas** [comment]
Right now, Spot 2 expects the property name to be the actual database column name, so there is no alias mapping support. This may not be that hard to implement, though.

**Comment by redstrike** [comment]
+1. "Alias mapping" is good for those has databases which were poorly designed in legacy systems. It's also helps page templates more concise because of short name properties.

**Comment by geggleto** [comment]
I am also :+1: for alias mapping... I have a 10 year old system i would like to migrate and I need to alias column names like `Phone 1`

**Comment by holywyvern** [comment]
The same problem here, My system has nasty columns names like 'acct_stop-time' or 'sBUsernameX'

**Comment by HipsterJazzbo** [comment]
@vlucas Forgive me if I'm wrong but... is this not the entire point of a data mapper? To separate the schema from your domain entities?

**Comment by nebulousGirl** [comment]
+1, would be useful for messy legacy databases.

**Comment by geggleto** [comment]
@HipsterJazzbo yes. but some of us have awesome column names like `Customer Account Number` and it would be lovely to alias that to something more sane.

**Comment by vlucas** [comment]
Yes, this is something that I absolutely do want to support. It just has not been done yet.

**Comment by geggleto** [comment]
Thanks for the update @vlucas I can't wait for this feature to be implemented!

**Comment by HipsterJazzbo** [comment]
@geggleto Sorry, yes, that's exactly what I'm saying. The "mapper" in "data mapper" refers to abstracting the database schema away from your entities. Without that, it's not *really* a data mapper :P

**Comment by geggleto** [comment]
@HipsterJazzbo Spot2 Entities are 100% coupled. Hence why we have the wonderful table generators.  Spot2 Entities are not meant to be domain entities.

**Comment by vlucas** [comment]
> Spot2 Entities are 100% coupled. Hence why we have the wonderful table generators. Spot2 Entities are not meant to be domain entities.

This. Exactly.

Any time you create an architecture for a project or a code library, you have to make some tradeoffs. When creating Spot2, I originally tried to use POPOs (plain old PHP objects - no hierarchy or class extension required), but the reality of the development was that it was simply far easier to provide a base `Spot\Entity` and require Entities to extend it. This is the approach Doctrine takes, but the reality of their codebase is that proxies have to be used instead, and you still have to put a bunch of annotation markup in your entity object anyways, so it defeats the purpose.

The tradeoff is that Spot2 is not a "*true* data mapper" (hello "No True Scotsman") in the strictest sense of the word, but instead that it uses the general data mapper paradigm for saving/retrieving entities in the code you use as you might expect (mapper saves/retrieves entities and collections, etc. instead of entities saving themselves).

The aim here is for developer happiness and large efficiency gains, and I am almost always willing to make tradeoffs to achieve that rather than worshiping at the alter of Martin Fowler.

**Comment by HipsterJazzbo** [comment]
Sorry, I didn't mean to cause any offence. I find myself in a situation where I do actually NEED a "true data mapper", and there doesn't seem to be one around. Thanks.

**Comment by geggleto** [comment]
@HipsterJazzbo well, the way I work it is by having 2 different classes called 'Entities' My Spot2/Entities are not in my Domain namespace, however there are methods to help transfer the data from a Domain Entity into one or more spot2/entities. In my opinion, that is a way more specific problem than a single package could ever solve.

**Comment by vlucas** [comment]
@HipsterJazzbo I am not offended, so no worries. I just wanted to better explain some of the decisions behind why Spot2 is the way it is. In my experience, trying to create a *true* or *perfect* version of some design pattern as a goal almost always makes the thing harder to use and more complicated (see Agavi or Zend Framework 2 vs. Laravel or similar).

What I would suggest for you if you still want to use Spot2 for persistence, is that you create an additional layer in front of Spot2 entities that represent your domain layer. You can then create your own mappers to save those entities that then map them back to multiple other Spot2 entities/database tables, etc. depending on which fields are set (assuming your goal here is a single entity that is saved to multiple other tables instead of the 1:1 entity:table mapping in Spot2).
