### ISSUE TITLE
After load event?

### ISSUE THREAD

**Issue by brownrl** [vlucas/spot2#98]
Is there an after load event? For example.

```$record = $mapper->first(['something'=12]);```

$record has the spot object properties and etc. But would it be possible to have a "afterLoaded" event sent so that $record could have a "construction" of sorts. I could have a function to convert some values or bring in other values, add some properties etc...

**Comment by nebulousGirl** [comment]
At some point, I added it to my custom mapper by overriding the `prepareEntity` method: 

```
public function prepareEntity(EntityInterface $entity)
    {
        parent::prepareEntity($entity);

        $this->eventEmitter()->emit('afterLoad', [$entity, $this]);
    }
```
But, I opted out of this method and created a CollectionDecorator instead, see my gist: https://gist.github.com/nebulousGirl/0de895616d599bda81ae

I find the second approach much cleaner because it doesn't directly affect the entity which is the data holder.

**Comment by vlucas** [comment]
This seems like a good idea for an event to add into Spot itself. I should be able to work on this in a few days.

**Comment by kayladnls** [comment]
Yes, please. We need this for work.
